name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Check code
        run: pnpm run check

      - name: Unit tests
        run: pnpm run test

      - name: Build
        run: pnpm run build

      - id: semantic-release
        name: Run semantic-release
        run: pnpm semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push major version
        run: |
          major_version=$(echo ${{ steps.semantic-release.outputs.nextVer }} | cut -d '.' -f 1)
          git tag -f v$major_version
          git push origin --tags --force
        if: ${{ steps.semantic-release.outputs.nextVer != null }}
